# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

majority_rule_R2022A <- function(x, value_of_interest, ni, nw) {
    .Call(`_flexurba_majority_rule_R2022A`, x, value_of_interest, ni, nw)
}

majority_rule_R2023A <- function(x, adj_value, ignore_value, water_value, adj_ignore, ni, nw) {
    .Call(`_flexurba_majority_rule_R2023A`, x, adj_value, ignore_value, water_value, adj_ignore, ni, nw)
}

